M48
; DRILL file {KiCad (6.0.5)} date Fri Nov  8 16:15:20 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-08T16:15:20+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.210
%
G90
G05
T1
X57.192Y-76.75
X57.192Y-91.25
T2
X77.0Y-59.0
T0
M30
